namespace LabelVerification.Application.Verification.Batch;

/// <summary>
/// Thread-safe progress snapshot emitted while a batch is processed.
///
/// Technical item state is kept separate from regulatory PASS / REVIEW / FAIL.
/// CompletedItemResult allows the UI to display each result as soon as that
/// individual label finishes instead of waiting for the entire batch.
/// </summary>
public sealed record BatchVerificationProgress
{
    public required string BatchCorrelationId { get; init; }

    public required int TotalItems { get; init; }

    public required int CompletedItems { get; init; }

    public required int PassCount { get; init; }

    public required int ReviewCount { get; init; }

    public required int FailCount { get; init; }

    public required int ErrorCount { get; init; }

    public string? LastCompletedItemId { get; init; }

    /// <summary>
    /// Item associated with the current progress event.
    /// This identifier is generated by the batch UI and is safe for correlation.
    /// </summary>
    public string? ItemId { get; init; }

    /// <summary>
    /// Technical state for the item associated with this progress event.
    /// </summary>
    public BatchItemProcessingStatus? ItemProcessingStatus { get; init; }

    /// <summary>
    /// Populated when an individual label has completed processing.
    /// </summary>
    public BatchVerificationItemResult? CompletedItemResult { get; init; }

    public double PercentComplete =>
        TotalItems <= 0
            ? 0
            : CompletedItems * 100d / TotalItems;
}